# Generated by Django 4.2.14 on 2024-07-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=8)),
                ('department', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer'), ('MERN', 'MERN'), ('Android Developer', 'Android Developer')], max_length=20)),
            ],
            options={
                'db_table': 'myuser',
            },
        ),
    ]
