# Generated by Django 4.2.14 on 2024-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_book_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, default=2002, null=True),
        ),
    ]
