# Generated by Django 4.2.14 on 2024-07-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='technology',
            field=models.CharField(choices=[('Pythons', 'Pythons'), ('Javascript', 'Javascript'), ('React', 'React'), ('Android', 'Android'), ('Flutter', 'Flutter'), ('Java', 'Java')], max_length=400),
        ),
    ]
